export const API_DATE_FORMAT = 'YYYY-MM-DD'
export const SHORT_DISPLAY_DATE_FORMAT = 'DD/MM/YYYY'
export const FULL_DISPLAY_DATE_FORMAT = 'DD MMM YYYY'
export const SHORT_DISPLAY_STRING_DATE_FORMAT = 'D MMM YYYY'
