import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="flex w-full h-full bg-[#090909]">
          <div className="w-[242px] h-full bg-red-500">
            <h1>Sidebar component here, pas aussi large, mettre du w-fit</h1>
          </div>
          {children}
        </div>
      </body>
    </html>
  )
}
