import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/organisms/Navbar/Navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="flex w-full h-full bg-[#090909]">
          <Navbar studentName="Nicolas B." applicationNumber={2} />
          {children}
        </div>
      </body>
    </html>
  )
}
