import {
  ActivityIcon,
  AirplayIcon,
  AlertCircleIcon,
  AlertHexagonIcon,
  AlertTriangleIcon,
  AlienIcon,
  AlignCenterIcon,
  AlignJustifyIcon,
  AlignLeftIcon,
  AlignRightIcon,
  ArchiveIcon,
  ArrowDownIcon,
  ArrowDownLeftIcon,
  ArrowDownRightIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowUpLeftIcon,
  ArrowUpRightIcon,
  AtSignIcon,
  AwardIcon,
  BarChart2Icon,
  BarChartIcon,
  BatteryChargingIcon,
  BatteryIcon,
  BookIcon,
  BookmarkIcon,
  BookOpenIcon,
  BorderRadiusIcon,
  BoundingBoxIcon,
  BriefcaseIcon,
  BrowserIcon,
  CalendarIcon,
  Camera2Icon,
  CameraIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeft2Icon,
  ChevronLeftIcon,
  ChevronRight2Icon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClipboardCopyIcon,
  ClipboardIcon,
  ClipboardListIcon,
  ClockIcon,
  CloseIcon,
  CodeIcon,
  ColumnsIcon,
  CommandIcon,
  CompanyIcon,
  CompassIcon,
  CopyIcon,
  CPUIcon,
  CreditCardIcon,
  CropIcon,
  CrossHairIcon,
  CursorIcon,
  DatabaseIcon,
  DeviceMobileIcon,
  DeviceTabletIcon,
  DiscIcon,
  DocumentAddIcon,
  DocumentDownloadIcon,
  DocumentIcon,
  DocumentRemoveIcon,
  DocumentReportIcon,
  DocumentTextIcon,
  DownloadIcon,
  EthereumIcon,
  ExternalLinkIcon,
  EyeBlinkIcon,
  EyeIcon,
  FigmaIcon,
  FilmIcon,
  FilterIcon,
  FilterLineIcon,
  FolderAddIcon,
  FolderDownloadIcon,
  FolderIcon,
  FolderRemoveIcon,
  GearIcon,
  GitBranchIcon,
  GitCommitIcon,
  GitMergeIcon,
  GitPullRequestIcon,
  GrabHandleIcon,
  GridAddIcon,
  GridIcon,
  GridRemoveIcon,
  HappyHomeIcon,
  HardDriveIcon,
  HeadphonesIcon,
  HexagonIcon,
  HomeIcon,
  InboxIcon,
  InformationIcon,
  InputIcon,
  ItalicIcon,
  KeyDownIcon,
  KeyLeftIcon,
  KeyRightIcon,
  KeyUpIcon,
  LayersIcon,
  LayoutIcon,
  LinkIcon,
  LockIcon,
  MailIcon,
  MailOpenIcon,
  MapIcon,
  MapPinIcon,
  MenuIcon,
  MicIcon,
  MinusCircleIcon,
  MinusIcon,
  MinusSmallIcon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  NoteIcon,
  PanelLeftCloseIcon,
  PanelLeftIcon,
  PanelLeftInactiveIcon,
  PanelLeftOpenIcon,
  PanelRightCloseIcon,
  PanelRightIcon,
  PanelRightInactiveIcon,
  PanelRightOpenIcon,
  PauseCircleIcon,
  PauseIcon,
  PhotographIcon,
  PlaceholderIcon,
  PlayCircleIcon,
  PlayIcon,
  PlusCircleIcon,
  PlusIcon,
  PlusSmallIcon,
  PowerButtonIcon,
  QRCodeIcon,
  RowsIcon,
  RSSIcon,
  SearchIcon,
  ShieldIcon,
  SidebarIcon,
  SlashBackwardIcon,
  SlashForwardIcon,
  SlidersIcon,
  SortIcon,
  SquareIcon,
  StackIcon,
  StarIcon,
  StrokeIcon,
  TargetIcon,
  TextIcon,
  TrashIcon,
  TVIcon,
  UnderlineIcon,
  UnlockIcon,
  UploadIcon,
  UserAddIcon,
  UserIcon,
  UserRemoveIcon,
  UsersIcon,
  Volume1Icon,
  Volume2Icon,
  VolumeIcon,
  VolumeMutedIcon,
  XIcon,
  ZapIcon,
  ZoomInIcon,
  ZoomOutIcon
} from '@/components/atoms'
import { IconName, IconProps } from '@/components/atoms/icons/types'

export const Icon = (props: IconProps) => {
  const iconsAsComponents: { [key in IconName]: JSX.Element } = {
    activity: <ActivityIcon {...props} />,
    airplay: <AirplayIcon {...props} />,
    'alert-circle': <AlertCircleIcon {...props} />,
    'alert-hexagon': <AlertHexagonIcon {...props} />,
    'alert-triangle': <AlertTriangleIcon {...props} />,
    alien: <AlienIcon {...props} />,
    'align-center': <AlignCenterIcon {...props} />,
    'align-justify': <AlignJustifyIcon {...props} />,
    'align-left': <AlignLeftIcon {...props} />,
    'align-right': <AlignRightIcon {...props} />,
    archive: <ArchiveIcon {...props} />,
    'arrow-down': <ArrowDownIcon {...props} />,
    'arrow-down-left': <ArrowDownLeftIcon {...props} />,
    'arrow-down-right': <ArrowDownRightIcon {...props} />,
    'arrow-left': <ArrowLeftIcon {...props} />,
    'arrow-right': <ArrowRightIcon {...props} />,
    'arrow-up': <ArrowUpIcon {...props} />,
    'arrow-up-left': <ArrowUpLeftIcon {...props} />,
    'arrow-up-right': <ArrowUpRightIcon {...props} />,
    award: <AwardIcon {...props} />,
    'at-sign': <AtSignIcon {...props} />,
    'bar-chart-2': <BarChart2Icon {...props} />,
    'bar-chart': <BarChartIcon {...props} />,
    'battery-charging': <BatteryChargingIcon {...props} />,
    battery: <BatteryIcon {...props} />,
    book: <BookIcon {...props} />,
    bookmark: <BookmarkIcon {...props} />,
    'book-open': <BookOpenIcon {...props} />,
    'border-radius': <BorderRadiusIcon {...props} />,
    'bounding-box': <BoundingBoxIcon {...props} />,
    briefcase: <BriefcaseIcon {...props} />,
    browser: <BrowserIcon {...props} />,
    calendar: <CalendarIcon {...props} />,
    'camera-2': <Camera2Icon {...props} />,
    camera: <CameraIcon {...props} />,
    check: <CheckIcon {...props} />,
    'chevron-down': <ChevronDownIcon {...props} />,
    'chevron-left-2': <ChevronLeft2Icon {...props} />,
    'chevron-left': <ChevronLeftIcon {...props} />,
    'chevron-right-2': <ChevronRight2Icon {...props} />,
    'chevron-right': <ChevronRightIcon {...props} />,
    'chevron-up': <ChevronUpIcon {...props} />,
    'clipboard-copy': <ClipboardCopyIcon {...props} />,
    clipboard: <ClipboardIcon {...props} />,
    'clipboard-list': <ClipboardListIcon {...props} />,
    clock: <ClockIcon {...props} />,
    close: <CloseIcon {...props} />,
    code: <CodeIcon {...props} />,
    columns: <ColumnsIcon {...props} />,
    command: <CommandIcon {...props} />,
    company: <CompanyIcon {...props} />,
    compass: <CompassIcon {...props} />,
    copy: <CopyIcon {...props} />,
    cpu: <CPUIcon {...props} />,
    'credit-card': <CreditCardIcon {...props} />,
    crop: <CropIcon {...props} />,
    crosshair: <CrossHairIcon {...props} />,
    cursor: <CursorIcon {...props} />,
    database: <DatabaseIcon {...props} />,
    'device-mobile': <DeviceMobileIcon {...props} />,
    'device-tablet': <DeviceTabletIcon {...props} />,
    disc: <DiscIcon {...props} />,
    'document-add': <DocumentAddIcon {...props} />,
    'document-download': <DocumentDownloadIcon {...props} />,
    document: <DocumentIcon {...props} />,
    'document-remove': <DocumentRemoveIcon {...props} />,
    'document-report': <DocumentReportIcon {...props} />,
    'document-text': <DocumentTextIcon {...props} />,
    download: <DownloadIcon {...props} />,
    ethereum: <EthereumIcon {...props} />,
    'external-link': <ExternalLinkIcon {...props} />,
    'eye-blink': <EyeBlinkIcon {...props} />,
    eye: <EyeIcon {...props} />,
    figma: <FigmaIcon {...props} />,
    film: <FilmIcon {...props} />,
    filter: <FilterIcon {...props} />,
    'filter-line': <FilterLineIcon {...props} />,
    'folder-add': <FolderAddIcon {...props} />,
    folder: <FolderIcon {...props} />,
    'folder-download': <FolderDownloadIcon {...props} />,
    'folder-remove': <FolderRemoveIcon {...props} />,
    gear: <GearIcon {...props} />,
    'git-branch': <GitBranchIcon {...props} />,
    'git-commit': <GitCommitIcon {...props} />,
    'git-merge': <GitMergeIcon {...props} />,
    'git-pull-request': <GitPullRequestIcon {...props} />,
    'grab-handle': <GrabHandleIcon {...props} />,
    'grid-add': <GridAddIcon {...props} />,
    grid: <GridIcon {...props} />,
    'grid-remove': <GridRemoveIcon {...props} />,
    'happy-home': <HappyHomeIcon {...props} />,
    'hard-drive': <HardDriveIcon {...props} />,
    headphones: <HeadphonesIcon {...props} />,
    hexagon: <HexagonIcon {...props} />,
    home: <HomeIcon {...props} />,
    inbox: <InboxIcon {...props} />,
    information: <InformationIcon {...props} />,
    input: <InputIcon {...props} />,
    italic: <ItalicIcon {...props} />,
    'key-down': <KeyDownIcon {...props} />,
    'key-left': <KeyLeftIcon {...props} />,
    'key-right': <KeyRightIcon {...props} />,
    'key-up': <KeyUpIcon {...props} />,
    layers: <LayersIcon {...props} />,
    layout: <LayoutIcon {...props} />,
    link: <LinkIcon {...props} />,
    lock: <LockIcon {...props} />,
    mail: <MailIcon {...props} />,
    'mail-open': <MailOpenIcon {...props} />,
    map: <MapIcon {...props} />,
    'map-pin': <MapPinIcon {...props} />,
    menu: <MenuIcon {...props} />,
    mic: <MicIcon {...props} />,
    'minus-circle': <MinusCircleIcon {...props} />,
    minus: <MinusIcon {...props} />,
    'minus-small': <MinusSmallIcon {...props} />,
    'more-horizontal': <MoreHorizontalIcon {...props} />,
    'more-vertical': <MoreVerticalIcon {...props} />,
    note: <NoteIcon {...props} />,
    'panel-left-close': <PanelLeftCloseIcon {...props} />,
    'panel-left': <PanelLeftIcon {...props} />,
    'panel-left-inactive': <PanelLeftInactiveIcon {...props} />,
    'panel-left-open': <PanelLeftOpenIcon {...props} />,
    'panel-right-close': <PanelRightCloseIcon {...props} />,
    'panel-right': <PanelRightIcon {...props} />,
    'panel-right-inactive': <PanelRightInactiveIcon {...props} />,
    'panel-right-open': <PanelRightOpenIcon {...props} />,
    'pause-circle': <PauseCircleIcon {...props} />,
    pause: <PauseIcon {...props} />,
    photograph: <PhotographIcon {...props} />,
    placeholder: <PlaceholderIcon {...props} />,
    'play-circle': <PlayCircleIcon {...props} />,
    play: <PlayIcon {...props} />,
    'plus-circle': <PlusCircleIcon {...props} />,
    plus: <PlusIcon {...props} />,
    'plus-small': <PlusSmallIcon {...props} />,
    'power-button': <PowerButtonIcon {...props} />,
    'qr-code': <QRCodeIcon {...props} />,
    rows: <RowsIcon {...props} />,
    rss: <RSSIcon {...props} />,
    search: <SearchIcon {...props} />,
    shield: <ShieldIcon {...props} />,
    sidebar: <SidebarIcon {...props} />,
    'slash-backward': <SlashBackwardIcon {...props} />,
    'slash-forward': <SlashForwardIcon {...props} />,
    sliders: <SlidersIcon {...props} />,
    sort: <SortIcon {...props} />,
    square: <SquareIcon {...props} />,
    stack: <StackIcon {...props} />,
    star: <StarIcon {...props} />,
    stroke: <StrokeIcon {...props} />,
    target: <TargetIcon {...props} />,
    text: <TextIcon {...props} />,
    trash: <TrashIcon {...props} />,
    tv: <TVIcon {...props} />,
    underline: <UnderlineIcon {...props} />,
    unlock: <UnlockIcon {...props} />,
    upload: <UploadIcon {...props} />,
    'user-add': <UserAddIcon {...props} />,
    user: <UserIcon {...props} />,
    'user-remove': <UserRemoveIcon {...props} />,
    users: <UsersIcon {...props} />,
    'volume-1': <Volume1Icon {...props} />,
    'volume-2': <Volume2Icon {...props} />,
    volume: <VolumeIcon {...props} />,
    'volume-muted': <VolumeMutedIcon {...props} />,
    x: <XIcon {...props} />,
    zap: <ZapIcon {...props} />,
    'zoom-in': <ZoomInIcon {...props} />,
    'zoom-out': <ZoomOutIcon {...props} />
  }

  return iconsAsComponents[props.name]
}
